import './globals.css'
import { Inter } from 'next/font/google'
import classNames from 'classnames'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'T-shirt 定制',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: any) {
  return (
    <html lang="zh-hans">
      <body className={classNames(inter.className, 'touch-none overflow-hidden')}>{children}</body>
    </html>
  )
}
